# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

require 'google/protobuf'


descriptor_data = "\n\nuser.proto\"\x83\x01\n\x07Picture\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05width\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r\x12\"\n\x04type\x18\x04 \x01(\x0e\x32\x14.Picture.PictureType\")\n\x0bPictureType\x12\x07\n\x03PNG\x10\x00\x12\x08\n\x04JPEG\x10\x01\x12\x07\n\x03GIF\x10\x02\"\xd7\x01\n\x04User\x12\n\n\x02id\x18\x01 \x01(\r\x12\x10\n\x08nickname\x18\x02 \x01(\t\x12\x14\n\x0cmail_address\x18\x03 \x01(\t\x12!\n\tuser_type\x18\x04 \x01(\x0e\x32\x0e.User.UserType\x12\x1b\n\tuser_icon\x18\x05 \x03(\x0b\x32\x08.Picture\x12\x17\n\x0f\x64\x65\x66\x61ult_picture\x18\x06 \x01(\r\"B\n\x08UserType\x12\n\n\x06NORMAL\x10\x00\x12\x11\n\rADMINISTRATOR\x10\x01\x12\t\n\x05GUEST\x10\x02\x12\x0c\n\x08\x44ISABLED\x10\x03\"\x19\n\x0bUserRequest\x12\n\n\x02id\x18\x01 \x01(\r\"C\n\x0cUserResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x04user\x18\x03 \x01(\x0b\x32\x05.User23\n\x0bUserManager\x12$\n\x03get\x12\x0c.UserRequest\x1a\r.UserResponse\"\x00\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

Picture = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Picture").msgclass
Picture::PictureType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Picture.PictureType").enummodule
User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("User").msgclass
User::UserType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("User.UserType").enummodule
UserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("UserRequest").msgclass
UserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("UserResponse").msgclass
